[phases.setup]
aptPkgs = [
    "gettext",
    "tzdata",
    "binutils",
    "libproj-dev",
    "gdal-bin",
    "libgdal-dev",  # Add this
    "python3-gdal"  # Add this
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install GDAL==$(gdal-config --version)",  # Install matching GDAL Python package
    "pip install -r requirements.txt"
]

[environment]
GDAL_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/libgdal.so"
GEOS_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/libgeos_c.so"
PROJ_LIB = "/usr/share/proj"
