[phases.setup]
aptPkgs = [
    "gettext",
    "tzdata",
    "binutils",
    "libproj-dev",
    "gdal-bin",
    "libgdal-dev",
    "python3-gdal",
    "python3-pip",
    "python3-dev",
    "gcc",
    "g++",
    "libpq-dev",
    "libheif-dev",     # Add this for libheif.so.1
    "libheif1",        # Add this for the runtime library
    "libsqlite3-dev",  # Common dependency
    "libgeos-dev",     # GEOS dependency
    "libproj-dev",     # PROJ dependency
    "proj-data",       # PROJ data
    "proj-bin"         # PROJ binary tools
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "echo 'GDAL library location:' $(find /usr -name 'libgdal.so*')", # This will print the location
    "pip install -r requirements.txt"
]

[variables]
USE_NIXPACKS = "True"
GDAL_LIBRARY_PATH = "/usr/lib/libgdal.so.30"
GEOS_LIBRARY_PATH = "/usr/lib/libgeos_c.so.30"
