[phases.setup]
aptPkgs = [
    "gettext",
    "tzdata",
    "binutils",
    "libproj-dev",
    "gdal-bin"
]

[environment]
GDAL_LIBRARY_PATH = "/usr/lib/libgdal.so"
GEOS_LIBRARY_PATH = "/usr/lib/libgeos_c.so"
