[phases.setup]
aptPkgs = [
    "gettext",
    "tzdata",
    "binutils",
    "libproj-dev",
    "gdal-bin",
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "echo 'GDAL library location:' $(find /usr -name 'libgdal.so*')", # This will print the location
    "pip install -r requirements.txt"
]

[variables]
USE_NIXPACKS = "True"
GDAL_LIBRARY_PATH = "/usr/lib/libgdal.so.30"
GEOS_LIBRARY_PATH = "/usr/lib/libgeos_c.so.30"
