# Generated by Django 5.0.6 on 2025-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the cron job', max_length=100, verbose_name='description')),
                ('type', models.CharField(choices=[('all_sync_odoo', 'all_sync_odoo'), ('rebuild_index', 'rebuild_index'), ('compliance_morning', 'compliance_morning'), ('compliance_afternoon', 'compliance_afternoon')], help_text='Type of cron job to execute', max_length=50, verbose_name='Cron Job Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cron job is active', verbose_name='active')),
            ],
            options={
                'verbose_name': 'Cron Job',
                'verbose_name_plural': 'Cron Jobs',
                'ordering': ['type'],
                'indexes': [models.Index(fields=['type'], name='core_cronjo_type_0e0781_idx'), models.Index(fields=['is_active'], name='core_cronjo_is_acti_4b584e_idx')],
            },
        ),
    ]
