# Generated by Django 5.0.6 on 2025-01-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if this instance is currently active', verbose_name='active')),
                ('type', models.SlugField(choices=[('bar', 'bar'), ('disco', 'discotek'), ('restaurant', 'restaurant'), ('store', 'store'), ('general', 'general'), ('warehouse', 'warehouse')], default='general', verbose_name='type')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='core/places/portraits/', verbose_name='portrait')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/places/logos/', verbose_name='logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('dispatch_address', models.BooleanField(default=False, help_text='Indicates if this place can be used for dispatching', verbose_name='dispatch address')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='core.address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], db_index=True, verbose_name='weekday')),
                ('open_time', models.TimeField(help_text='Time when the place opens', verbose_name='open time')),
                ('close_time', models.TimeField(help_text='Time when the place closes', verbose_name='close time')),
                ('place', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.place', verbose_name='place')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'ordering': ['weekday', 'open_time'],
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='core_place_name_113002_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['type'], name='core_place_type_de8a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['weekday', 'open_time'], name='core_period_weekday_cad60c_idx'),
        ),
    ]
